Test: End2end test for interactive mode

diff --git a/teste2e b/teste2e
--- a/teste2e
+++ b/teste2e
@@ -3,8 +3,10 @@
 VIRTUALENV="virtualenv"
 MKTEMP="mktemp"
 DEBUG=0
-TESTMOVIE="Fight.Club.1995.BluRay.720p.x264.DTS-SPARKS.mkv"
-EXPECTED="Fight Club (1999)"
+TESTMOVIE1="Fight.Club.1995.BluRay.720p.x264.DTS-SPARKS.mkv"
+TESTMOVIE2="Forrest.Gump.1994.DVDRip.DivX-CHD.avi"
+EXPECTED1="Fight Club (1999)"
+EXPECTED2="Forrest Gump (1994) (comment)"  # Used to test manual naming
 
 ################################################################################
 # Functions
@@ -69,9 +71,11 @@ debug "TEMPDIR: $TEMPDIR"
 # 1) Test set-up
 ################################################################################
 
-MOVIEFILE="$TEMPDIR"/"$TESTMOVIE"
+MOVIEFILE1="$TEMPDIR"/"$TESTMOVIE1"
+MOVIEFILE2="$TEMPDIR"/"$TESTMOVIE2"
 IMDBTAG="$TEMPDIR"/bin/imdbtag
-touch "$MOVIEFILE"
+touch "$MOVIEFILE1"
+touch "$MOVIEFILE2"
 
 echo "Creating virtual environment"
 "$VIRTUALENV" "$TEMPDIR" 2>&1 | sed 's/^/- /' \
@@ -88,21 +92,40 @@ echo "Installing imdbtag"
 
 echo "Executing $IMDBTAG in offline mode"
 	
-CMD="$IMDBTAG $VERBOSE -os $MOVIEFILE"
+CMD="$IMDBTAG $VERBOSE -os $MOVIEFILE1"
 debug "Command: '$CMD'"
 $CMD | sed 's/^/- /' \
-	|| die "Error running $IMDBTAG"
+	|| die "Error running $CMD"
+
+CMD="$IMDBTAG $VERBOSE $MOVIEFILE2"
+debug "Command: '$CMD'"
+echo -e "\n\nForrest Gump (1994) (comment)\n\n" | $CMD | sed 's/^/- /' \
+	|| die "Error running $CMD with input"
 
 
 ################################################################################
 # 3) Verify
 ################################################################################
 
-if [ ! -d "$TEMPDIR"/"$EXPECTED" ]; then
-	echo "Test failed: Directory \"$TEMPDIR/$EXPECTED\" not found"
-	abort
+FAIL=0
+
+if [ ! -d "$TEMPDIR"/"$EXPECTED1" ]; then
+	echo "Test 1 failed: Directory \"$TEMPDIR/$EXPECTED1\" not found"
+	FAIL=1
 else
-	echo "Test PASSED!"
+	echo "Test 1 PASSED!"
+fi
+
+if [ ! -d "$TEMPDIR"/"$EXPECTED2" ]; then
+	echo "Test 2 failed: Directory \"$TEMPDIR/$EXPECTED2\" not found"
+	FAIL=1
+else
+	echo "Test 2 PASSED!"
+fi
+
+if [ $FAIL -eq 1 ]; then
+	echo "Some tests failed!"
+	abort
 fi
 
 cleanup
